version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "12:00"
    timezone: Europe/Brussels
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: postcss
    versions:
    - 8.2.2
    - 8.2.4
    - 8.2.6
  - dependency-name: stylelint
    versions:
    - 13.11.0
    - 13.9.0
  - dependency-name: sass
    versions:
    - 1.32.0
    - 1.32.5
    - 1.32.8
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.8
  - dependency-name: xo
    versions:
    - 0.37.1
    - 0.38.2
  - dependency-name: postcss-load-config
    versions:
    - 3.0.1
  - dependency-name: autoprefixer
    versions:
    - 10.2.4
  - dependency-name: gulp-terser
    versions:
    - 2.0.1
  - dependency-name: update-notifier
    versions:
    - 5.1.0
  - dependency-name: browser-sync
    versions:
    - 2.26.14
