version: 2.1

_common: &common
  steps:
    - checkout
    - restore_cache:
        keys:
          - "{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum \".circleci/config.yml\" }}-{{ checksum \"package-lock.json\" }}"
          - "{{ .Environment.CIRCLE_JOB }}-{{ checksum \".circleci/config.yml\" }}-{{ checksum \"package-lock.json\" }}"
        name: Restore npm modules
    - run: node --version
    - run: npm --version
    - run: npm ci
    - save_cache:
        key: "{{ .Environment.CIRCLE_JOB }}-{{ .Branch }}-{{ checksum \".circleci/config.yml\" }}-{{ checksum \"package-lock.json\" }}"
        name: Save npm modules
        paths:
          - ~/.npm/
    - run: npm test

jobs:
  node-8:
    docker:
      - image: circleci/node:8-stretch
    <<: *common

  node-10:
    docker:
      - image: circleci/node:10-stretch
    <<: *common

  node-12:
    docker:
      - image: circleci/node:12-stretch
    <<: *common

workflows:
  version: 2
  test:
    jobs:
      - node-8
      - node-10
      - node-12
